# Generated by Django 4.1.7 on 2023-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_slot',
            field=models.SmallIntegerField(),
        ),
    ]
