# Generated by Django 4.1.4 on 2023-04-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_slot')},
        ),
    ]
